### PR TITLE
added qpOASES-3.2.0 for standard ACADO and qpOASES_e-3.1.1 for ACADO …

### PR DESCRIPTION
**Pull request by ferreau**
…CGT; few more tiny adjustments to make code compile under cygwin

### CODE REVIEW

**Comment by mvukov** [comment]
I didn't explicitly check implementation of reduced Hessian and corresponding factorization... @ferreau, have you benchmarked mine, in the older qpoases embedded, and the one you provided in this pull request?

**Comment by mvukov** [comment]
The bottom line: is @ferreau 's "new" implementation faster than the old one?

**Comment by ferreau** [comment]
I have not compared the "old" qpOASES embedded (based on qpOASES-1.3) and the "new" one, qpOASES_e-3.1.1 in terms of speed. 

Actually, I expect the new one to be up to a factor 2 slower on very small QPs. Probably, qpOASES_e can still benefit from a thorough profling. One the other hand, qpOASES_e-3.1.1 is expected to be significantly more reliable. That's why I kept both versions for the time being, such that the user can choose. 

My personal take is to use QP_QPOASES3 whenever reliability is critical and resort to QP_QPOASES only if reliability is not your main concern and computational time is at a premium.

**Comment by ferreau** [comment]
Btw, qpOASES in standard ACADO is a different story: here, I suggest to simply delete the qpOASES-3.0beta version (I kept it just in case there are issues with the new version, but it is currently not even compiled anymore).

**Comment by mvukov** [comment]
OK, thanx for the reply. I can check the reduced Hessian related computations when I have more time. Thanks for updating ACADO :)

**Comment by rienq** [comment]
@ferreau: there were three files which I believe got changed by accident in the last pull request, the commit above hopefully fixed that

**Comment by ferreau** [comment]
I fully agree, thanks for fixing this! Hopefully, I did not introduce more hick-ups...

**Pull request merged**
