### PR TITLE
Some performance improvements for when OCP is called in a loop

### PR DESCRIPTION
**Pull request by skaynama**
These are two minor changes that I believe improve the code execution speed in the case where OCP is recursively called in a loop. One is very non-intrusive (it changes when an SVD computation is needed to be performed). As for the other (freeze condensing) I found that it improves speed while not affecting the results in any noticeable form. That said, I can undo this second change if you feel that it may cause instability.

### CODE REVIEW

**Comment by mikepurvis** [comment]
Looks like `ocp_active_damping_test` and `parameter_estimation_michaelis_menten_test` don't like the freeze condensing change, so either that change should be reversed, or the tests updated.

What's the best path forward here? @rienq @mvukov

**Comment by mvukov** [comment]
Ping @borishouska @ferreau  Those two guys implemented it :)

**Comment by skaynama** [comment]
I just commented out the condense freezing (reverted back the change) so that the tests don't fail. The remaining change has very low impact on ACADO yet it'll still improve performance considerably for when ACADO functions are called in a loop. Please consider merging.

@mvukov Milan, I'm still going to take your advice and give code-gen a shot. In the meantime this will provide a temporary solution. :)

**Comment by mvukov** [comment]
OK, this seems all fine to me. @rienq please merge this pull request to the master. I am in a middle of transition to another computer...

**Comment by skaynama** [comment]
Great, thanks for reviewing it Milan. Please consider merging into the stable branch (not the master branch).

**Comment by skaynama** [comment]
Any progress on this PR?  @rienq 
This is really a minor change. The sole purpose of the SVD computation was to issue a warning. This is a computationally expensive check and does not have to be done if the log levels are set not to display any warnings! Moving it in the if block improves the performance of calling ACADO in a loop significantly.

Since @mvukov has already reviewed and approved it, please consider merging into the stable branch so we can go ahead and update the ROS distro.

**Comment by rienq** [comment]
This looks all fine to me! Sorry for the delay.. I'm not sure why I had to do the PR though :-)

**Comment by skaynama** [comment]
Thanks @rienq . I tagged you only because your name was mentioned in a previous comment. Who would be the right person to tag for future PRs?

**Pull request merged**
